---
title: "RBC_Manuscripts for pulication-blood stream"
format: html
editor: visual
---

## Data cleaning and analysis

```{r}

## loading for the libraries
library(readxl)
library(tidyverse)
library(tidyr)
library(lubridate)
## set working directory
# Setting working directory

wd = "C:/RBC_Manuscripts"
data_wd = paste0(wd,"/data")
output_wd = paste0(wd,"/outputs_and_graphics")
## uploading the data set 
setwd(data_wd)
data = read_excel("AMR Data.xlsx",sheet = "Sheet 1") %>% 
    janitor::clean_names()

# Keeping only blood sample type

blood <- data %>% 
  filter(`Human sample type`=="Blood") # We remained with 1,642

# Keeping only sample collected in 2020 or beyond
blood <- blood %>%
  mutate(across(.cols = where(is.POSIXct), .fns = as.Date)) %>% 
  mutate(yscd=year(`Sample collection date`)) %>% 
  filter(yscd>=2020)

# Remove duplicates

blood <- blood %>% 
  distinct()
```

## cleaning the variables of interest from data frame

```{r}
#Finding the age in years using two dates provided
# Age
blood <-blood %>%
  mutate(age_new = round(as.numeric(difftime(blood$`Enrollment date`,   blood$`Date of birth`, units = "days")) / 365))


```

```{r}
# Exporting the data
export(blood, "data_Today.xlsx") # will save to working directory
```

```{r}

blood <- blood %>% 
  mutate(Age_cat = case_when(
    age_new >= 0 & age_new <=2          ~ "0-2 YEARS",
    age_new >= 3 & age_new <=15         ~ "3-15 YEARS",
    age_new >= 16 & age_new <=45        ~ "16-45 YEARS",
    age_new >45                         ~ ">45 yEARS",
    is.na(age_new)                     ~ NA_character_,
    TRUE                               ~ "Check me"))  
```

```{r}
# cleaning for most common antibiotics used 
blood<-blood %>% 
  select(`Organisation unit name`,Gender,Address,`Requesting Department`,`Human sample type`,`Pathogen growth`,`Pathogen Type`,`Pathogen Type_Grp`,Amikacin,Amoxicillin ,`Amoxicillin-clavulanic acid`,Ampicillin,Cefotaxime,Ceftriaxone,Cefuroxime,Chloramphenicol,Ciprofloxacin,Clindamycin,Erythromycin,Gentamicin,Imipenem,Meropenem,Levofloxacin,Oxacillin,Penicillin,Vancomycin,Age_cat,`Event date`,`Enrollment date`,`Date of birth`,`Sample collection date`,age_new,yscd)  
 
```

```{r}

```
